<footer class="fixed-bottom bg-yellowgreen" align="center">
		<p class="text-black-50">
			<strong>&blacktriangleleft;</strong>
			<a class="fab fa-github" href="https://github.com/SanJeosutin?tab=repositories"></a> SanJeosutin |
			<a class="fab fa-discord" href="#Jury_Quackington#6116"></a> Jury Quackinton#6116 |
			<a class="fa fa-envelope" href="mailto:contact.justin@sanjustin.xyz"> </a> Justin S.
			<strong>&blacktriangleright;</strong>
		</p>
	</footer>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
		integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
		crossorigin="anonymous"></script>
</body>

</html>