<nav class="navbar navbar-expand-md navbar-light bg-greenyellow" >
		<div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navBarAlt">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-item nav-link active" href="projects.php">Projects</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-item nav-link" href="about.php">About</a>
				</li>
				<li class="nav-item">
					<a class="nav-item nav-link" href="designs.php">Designs</a>
				</li>
			</ul>
		</div>
		<div class="mx-auto order-0">
			<a class="navbar-brand font-weight-bold index-font" href="index.php">San Justin </a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBarAlt" aria-controls="navBarAlt" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		</div>

		<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link fas fa-adjust" href="#"></a>
				</li>
			</ul>
		</div>
	</nav>